server:
    port: 8081
    servlet:
        context-path: /eureka

spring:
    application:
        #Eureka程序名称
        name: eureka-server
        #配置 eureka 页面的登陆的账号和密码,需要配合security依赖使用

    security:
        user:
            name: root
            password: 123456

eureka:
    client:
        #是否启用湖区注册服务信息，因为这是一个单节点的EurekaServer，不需要同步其他的EurekaServer节点的数据，所以设置为false；
        fetch-registry: false
        #表示是否向eureka注册服务，即在自己的eureka中注册自己，默认为true，此处应该设置为false；
        register-with-eureka: false
        service-url:
            defaultZone:  http://root:123456@localhost:8081/eureka/eureka
    instance:
        #显示IP地址
        prefer-ip-address: true
        #默认值为：机器名称：服务名称：实例得端口，一般需要机器名称，按照以下模式修改即可
        instance-id: ${spring.application.name}:${server.port}
        hostname: localhost

    server:
        #设为false，关闭自我保护，即Eureka server在云心光器件会去统计心跳失败比例在15分钟之内是否低于85%,如果低于85%，EurekaServer
        #会将这些事例保护起来，让这些事例不会过期，但是在保护器内如果刚哈这个服务提供者非正常下线了，此时服务消费者会拿到一个无效的服务
        #实例，此时调用会失败，对于这个问题需要服务消费者端有一些容错机制，如重试、断路器等；
        enable-self-preservation: false
        #扫描失效服务的间隔时间（单位是毫秒，摩恩是60*1000)，即60s
        eviction-interval-timer-in-ms: 10000
