spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      resolve-lazily: false
  #      location: H:/
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
#    password: 123456
    password: YY&yt123456
    type:  com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
  #redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 60
    jedis:
      pool:
        #最大空闲时间，数据库连接的最大空闲时间。超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
        max-idle: 300
        #连接池的最大数据库连接数。设为0表示无限制
        max-active: 600
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 1000
        #default.db: 0
        #password: 123456

server:
  port: 8087

mybatis:
  mapper-locations: classpath:Mapper/*.xml

eureka:
  instance:
    #显示IP地址
    prefer-ip-address: true
    #默认值为：机器名称：服务名称：实例得端口
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8081/eureka/eureka

